'use strict';
const P=Pref, names=['Вы','Алексей','Мария'], $=id=>document.getElementById(id);let state,selected=[],paused=false,timer=null,speed=650;
let fresh=true,migrated=false;try{const saved=JSON.parse(localStorage.getItem('preferans-save'));migrated=saved?.version===1;state=P.restore(saved);fresh=!state;speed=Number(localStorage.getItem('preferans-speed'))||650;}catch{}if(!state){state=P.create();P.deal(state)}
const finalResults=document.createElement('section');finalResults.id='finalResults';finalResults.className='final-results';finalResults.hidden=true;finalResults.setAttribute('aria-live','polite');document.querySelector('.table-top').after(finalResults);
function number(value){return value.toLocaleString('ru-RU',{maximumFractionDigits:1})}
function signed(value){return (value>0?'+':'')+number(value)}
function dealsText(value){const last=value%10,lastTwo=value%100;return value+' '+(last===1&&lastTwo!==11?'раздача':last>=2&&last<=4&&(lastTwo<12||lastTwo>14)?'раздачи':'раздач')}
function winnerText(rows){const winners=rows.filter(r=>r.place===1).map(r=>names[r.player]);return winners.length===1?'Победитель — '+winners[0]:'Ничья: '+winners.join(', ')}
function renderResults(){const finished=state.phase==='finished';finalResults.hidden=!finished;document.querySelector('.felt').hidden=finished;document.querySelector('.hand-area').hidden=finished;if(!finished)return;const rows=P.standings(state);finalResults.innerHTML=`<span class="eyebrow">ВСЕ ПУЛИ ЗАКРЫТЫ</span><div class="trophy" aria-hidden="true">♛</div><h2>${winnerText(rows)}</h2><p>Пуля до ${state.target} · ${dealsText(state.round)}</p><div class="results-scroll"><table class="results-table"><thead><tr><th scope="col">Место</th><th scope="col">Игрок</th><th scope="col">Пуля</th><th scope="col">Гора</th><th scope="col">Висты</th><th scope="col">Итог</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.place===1?'winning-row':''}"><td>${r.place}</td><th scope="row">${names[r.player]}${r.place===1?' <span aria-label="Победитель">♛</span>':''}</th><td>${r.pool}</td><td>${number(r.hill)}</td><td>${signed(r.whists)}</td><td class="${r.total>=0?'positive':'negative'}">${signed(r.total)}</td></tr>`).join('')}</tbody></table></div><p class="result-note">Висты — разница взаимных записей. Итог учитывает пулю, гору и висты.<br>Места определяются по точным значениям; отображение округлено до десятых.</p>`;}
function save(){try{localStorage.setItem('preferans-save',JSON.stringify(state));localStorage.setItem('preferans-speed',speed)}catch{}}
function card(c,interactive=false,disabled=false){return `<${interactive?'button':'div'} class="card ${c.s>1?'red':''} ${selected.includes(c.id)?'selected':''}" ${interactive?`data-card="${c.id}" aria-label="${P.RANKS[c.r]} ${P.SUITS[c.s]}" aria-pressed="${selected.includes(c.id)}" ${disabled?'disabled':''}`:''}><span>${P.RANKS[c.r]}</span><span class="suit">${P.SUITS[c.s]}</span><span class="big-suit">${P.SUITS[c.s]}</span><span class="corner">${P.RANKS[c.r]}${P.SUITS[c.s]}</span></${interactive?'button':'div'}>`}
function options(bs){return bs.map(b=>`<option value="${b.id}">${b.label}</option>`).join('')}
function render(){save();$('hand').style.setProperty('--cards',Math.max(2,state.hands[0].length));$('hand').style.setProperty('--columns',state.hands[0].length>10?6:5);const phase=state.phase,playing=phase==='play',turn=state.turn;const labels={auction:'Торговля',discard:'Прикуп и снос',contract:'Заказ игры',whist:'Вистование',play:'Розыгрыш',trickEnd:'Взятка',result:'Раздача завершена',finished:'Партия завершена'};
$('phaseLabel').textContent=labels[phase];$('roundLabel').textContent=`Пуля до ${state.target} · раздача ${state.round}`;$('scoreRound').textContent=`До ${state.target}`;$('pauseButton').textContent=paused?'▶ Продолжить':'Ⅱ Пауза';$('pauseButton').disabled=phase==='finished';renderResults();
for(const p of [1,2]){$('player'+p).className='player '+(turn===p&&!['result','finished','trickEnd'].includes(phase)?'active':'');$('player'+p).innerHTML=`<span class="avatar ${p===2?'maria':''}">${p===1?'А':'М'}</span><div><b>${names[p]}</b><small>${state.tricks[p]} взяток · ${state.hands[p].length} карт</small><div class="back-row">${state.hands[p].map(()=>'<i class="back"></i>').join('')}</div></div>`}
document.querySelector('.self').classList.toggle('active',turn===0&&!['result','finished','trickEnd'].includes(phase));$('humanTricks').textContent=state.tricks[0]+' взяток';$('humanStatus').textContent=state.declarer===0?'Разыгрывающий':state.contract?.n===-1?'Избегайте взяток':state.whist?.[0]===true?'Вистующий':'Ваши карты';
$('contract').innerHTML=state.contract?`${state.declarer>=0?names[state.declarer]+' играет':''} <b>${state.contract.label}</b>`:state.high>=0?`Старшая заявка <b>${P.bids[state.high].label}</b>`:'ПРИКУП НА СТОЛЕ';
if(state.trick.length){$('trick').innerHTML=state.trick.map(t=>`<div class="played ${phase==='trickEnd'&&t.player===state.trickWinner?'winner':''}">${card(t.card)}<small>${names[t.player]}</small></div>`).join('')}else if(['discard','contract'].includes(phase)){$('trick').innerHTML=state.talon.map(c=>card(c)).join('')}else{$('trick').innerHTML=phase==='auction'?'<div class="card" style="background:repeating-linear-gradient(45deg,#b9cbb222 0 1px,transparent 1px 5px),#294d3c;border-color:#849a7788;transform:rotate(-8deg)"></div><div class="card" style="background:repeating-linear-gradient(45deg,#b9cbb222 0 1px,transparent 1px 5px),#294d3c;border-color:#849a7788;transform:rotate(8deg)"></div>':'<span style="font:42px Georgia;color:#b5ccb322">♠ ♣ ♦ ♥</span>'}
const f=state.contract?P.forced(state):-1;$('tableMessage').textContent=paused?'Игра на паузе':phase==='trickEnd'?`${names[state.trickWinner]} ${state.trickWinner===0?'забираете':'забирает'} взятку`:phase==='result'||phase==='finished'?state.result:playing&&f>=0?`Масть прикупа: ${P.SUITS[f]}`:playing?`${names[turn]} · ${turn===0?'ваш ход':'обдумывает ход'}`:phase==='auction'?'Оцените руку и вступайте в торги':'Прикуп открыт для всех игроков';
const allowed=playing&&turn===0?P.legal(state.hands[0],state.trick,state.contract.s,f).map(c=>c.id):[];const canDiscard=phase==='discard'&&state.declarer===0;$('hand').innerHTML=state.hands[0].map(c=>card(c,true,paused||(!canDiscard&&!allowed.includes(c.id)))).join('');$('handHint').textContent=canDiscard?`Выбрано ${selected.length} из 2`:playing&&turn===0?'Доступные карты подсвечены':`${state.hands[0].length} карт`;
const totals=P.totals(state);$('scores').innerHTML=state.scores.map((s,p)=>`<div class="score-row ${p===0?'you':''}"><span>${names[p]}${s.pool>=state.target?' ✓':''}</span><span>${s.pool}</span><span>${number(s.hill)}</span><span class="${totals[p]>=0?'positive':'negative'}">${signed(totals[p])}</span></div>`).join('');$('journal').innerHTML=state.log.slice(-8).map(l=>`<div>${l}</div>`).join('');$('journal').scrollTop=$('journal').scrollHeight;
let title='Боты обдумывают ход',hint='Ваш ход появится автоматически',actions='';if(phase==='finished'){title='Партия завершена';hint=winnerText(P.standings(state));actions='<button class="primary" data-action="new">Сыграть ещё</button><button data-action="history">История партии</button>'}else if(paused){title='Игра на паузе';hint='Карты и запись сохранены';actions='<button class="primary" data-action="resume">Продолжить</button>'}else if(phase==='auction'&&turn===0){const bs=P.available(state,0);title='Ваше слово';hint='Закажите игру или скажите «пас»';actions=bs.length?`<select id="bidSelect" aria-label="Заявка на торгах">${options(bs)}</select><button class="primary" data-action="bid">Торговаться</button>`:'';actions+='<button data-action="pass">Пас</button>'}else if(canDiscard){title='Выберите две карты для сноса';hint='Нажмите на карты в вашей руке';actions=`<button class="primary" data-action="discard" ${selected.length!==2?'disabled':''}>Снести две карты</button>`}else if(phase==='contract'&&state.declarer===0){const bs=P.bids.filter(b=>b.id>=state.high&&(state.contract.n===0?b.n===0:b.n>0));title='Закажите окончательную игру';hint='Заказ не может быть ниже заявки';actions=`<select id="contractSelect" aria-label="Контракт">${options(bs)}</select><button class="primary" data-action="declare">Играть</button>`}else if(phase==='whist'&&turn===0){title='Вист или пас?';hint='Обязательства: '+(state.contract.n===6?4:state.contract.n===7?2:state.contract.n<=9?1:0)+' взяток на защиту';actions='<button class="primary" data-action="whist">Вист</button><button data-action="whistPass">Пас</button>'}else if(playing&&turn===0){title='Ваш ход';hint=state.contract.n<=0?'Старайтесь избежать взяток':'Нажмите на карту, чтобы сыграть';}else if(phase==='trickEnd'){title='Взятка завершена';hint='Следующий ход за победителем';actions='<button data-action="collect">Продолжить ↗</button>'}else if(phase==='result'){title=state.result;hint='Взятки: '+state.tricks.join(' / ');actions='<button class="primary" data-action="next">Следующая раздача →</button>'}
$('actionTitle').textContent=title;$('actionHint').textContent=hint;$('actions').innerHTML=actions;$('tipText').textContent=canDiscard?'Снесите карты слабой масти, чтобы раньше получить возможность сыграть козырем.':state.contract?.n===0?'На мизере нужно остаться без взяток. Даже одна взятка означает подсад.':playing?'В масть нужно отвечать мастью. Если её нет — козырем. Если нет и козыря, можно сыграть любую карту.':'Пас окончателен: вернуться в торги в этой раздаче нельзя. Мизер можно объявить только первым своим словом.';schedule();}
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3500)}
function act(fn){clearTimeout(timer);try{fn();render()}catch(e){toast(e.message);schedule()}}
function schedule(){clearTimeout(timer);if(paused||$('modal').open)return;const phase=state.phase;if(phase==='trickEnd'){timer=setTimeout(()=>act(()=>P.collect(state)),speed*2);return}const p=state.turn;if((phase==='auction'||phase==='whist'||phase==='play')&&p===0)return;if((phase==='discard'||phase==='contract')&&state.declarer===0)return;if(['result','finished'].includes(phase))return;timer=setTimeout(()=>act(()=>{if(phase==='auction'){const b=P.botBid(state,p);P.bid(state,p,b?.id??null)}else if(phase==='discard')P.discard(state,P.botDiscard(state));else if(phase==='contract'){const q=state.declarer;const bs=P.bids.filter(b=>b.id>=state.high&&(state.contract.n===0?b.n===0:b.n>0));const best=bs.filter(b=>b.n===0||P.estimate(state.hands[q],b.s)>=b.n).at(-1)||bs[0];P.declare(state,best.id)}else if(phase==='whist'){const needed=state.contract.n===6?2:state.contract.n===7?1:.5;P.whist(state,p,P.estimate(state.hands[p],state.contract.s)>=needed)}else if(phase==='play')P.play(state,p,P.botCard(state,p).id)}),speed)}
$('hand').addEventListener('click',e=>{const c=e.target.closest('[data-card]');if(!c||c.disabled)return;const id=Number(c.dataset.card);if(state.phase==='discard'){if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<2)selected.push(id);else{toast('Выбраны две карты. Снимите выбор с одной из них.');return}render()}else act(()=>P.play(state,0,id))});
$('actions').addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='new'){newDialog();return}if(a==='history'){modal('<h2>История партии</h2>'+state.history.map(x=>`<p>${x.round}. ${x.label} (${x.tricks.join(' / ')})</p>`).join(''));return}act(()=>{if(a==='bid')P.bid(state,0,Number($('bidSelect').value));if(a==='pass')P.bid(state,0,null);if(a==='discard'){P.discard(state,selected);selected=[]}if(a==='declare')P.declare(state,Number($('contractSelect').value));if(a==='whist'||a==='whistPass')P.whist(state,0,a==='whist');if(a==='collect')P.collect(state);if(a==='next')P.deal(state);if(a==='resume')paused=false})});
function modal(html){clearTimeout(timer);$('modalContent').innerHTML=html;$('modal').showModal()}
function closeModal(){$('modal').close();schedule()}$('closeModal').onclick=closeModal;$('modal').addEventListener('close',schedule);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('pauseButton').onclick=()=>{paused=!paused;render()};
function newDialog(initial=false){modal('<h2>'+ (initial===true?'Добро пожаловать за стол':'Новая партия')+'</h2><p>'+(initial===true?'Выберите размер пули.':'Текущая партия будет заменена.')+' Играем, пока все три игрока не закроют пулю. Победит игрок с лучшим итогом в вистах.</p><label for="poolTarget">Размер пули</label> <select id="poolTarget"><option value="10">10 очков</option><option value="15">15 очков</option><option value="20">20 очков</option></select><p><button class="primary" id="confirmNew">Раздать карты</button></p>');$('poolTarget').value=state.target;$('confirmNew').onclick=()=>{const n=Number($('poolTarget').value);state=P.create(n);P.deal(state);selected=[];paused=false;closeModal();render()}}$('newButton').onclick=()=>newDialog();
$('settingsButton').onclick=()=>{modal('<h2>Темп игры</h2><p>Раздача сохраняется автоматически в этом браузере. Можно закрыть страницу и вернуться позже.</p><label>Скорость ботов <select id="speedSelect"><option value="350">Быстро</option><option value="650">Спокойно</option><option value="1200">Вдумчиво</option></select></label><p><button class="primary" id="saveSettings">Сохранить</button></p>');$('speedSelect').value=speed;$('saveSettings').onclick=()=>{speed=Number($('speedSelect').value);save();closeModal()}};
$('scoreDetailsButton').onclick=()=>modal('<h2>Взаимные висты</h2><p>Строка — кто записал, столбец — на кого.</p><table><tr><th></th>'+names.map(n=>'<th>'+n+'</th>').join('')+'</tr>'+state.scores.map((s,p)=>'<tr><th>'+names[p]+'</th>'+s.whists.map((v,q)=>'<td>'+(p===q?'—':v)+'</td>').join('')+'</tr>').join('')+'</table>');
$('rulesButton').onclick=()=>modal(`<h2>Как играем за этим столом</h2><p>Домашний вариант сочинки для трёх игроков. Выберите пулю на 10, 15 или 20 очков. Партия заканчивается после раздачи, в которой все три игрока закрыли пулю. Побеждает игрок с лучшим итогом в вистах; равные итоги дают общее место.</p><ol><li>Колода — 32 карты, от семёрки до туза. Каждому по 10 карт, две карты в прикупе.</li><li>Торги: 6 ♠, 6 ♣, 6 ♦, 6 ♥, 6 БК, затем семь и выше. Мизер старше 8 БК и младше 9 ♠. Он доступен только первым словом; после него можно только пасовать или остаться на мизере. Пас окончателен.</li><li>Победитель берёт открытый прикуп, сносит две карты и заказывает контракт не ниже заявки. На мизере нужно взять ноль взяток, на обычной игре — не меньше заказанного.</li><li>Защитники выбирают вист или пас. При двух пасах контракт записывается как сыгранный без розыгрыша. При одном висте защитники играют каждый своими картами; вистующий отвечает за их суммарные взятки. Здесь все игры разыгрываются втёмную.</li><li>В масть обязательно давать масть, при её отсутствии — козырь. Если нет обоих, разрешена любая карта. Старшая карта масти хода или старший козырь берёт взятку. Первая рука начинает розыгрыш.</li><li>При трёх пасах играются распасы без козыря. Масти первых двух взяток задаются картами прикупа. Каждый старается брать меньше взяток.</li></ol><h3>Закрытие пули</h3><p>Очки сначала закрывают свою пулю. Излишек идёт игроку с наибольшей незакрытой пулей; при равенстве — ближайшему по очереди хода. За каждое очко помощи записываются 10 вистов на получателя. Если после закрытия всех пуль остаётся излишек, он списывается с горы сыгравшего; гора может стать отрицательной.</p><h3>Запись и соглашения</h3><p>Стоимость игр 6–10: 2, 4, 6, 8, 10. Мизер — 10. Успех пишется в пулю, каждый недобор — стоимость игры в гору; на мизере каждая взятка стоит 10 в гору. Распасы — по 1 в гору за взятку, без прогрессии.</p><p>Вистующие получают стоимость игры за каждую взятку; при подсаде оба защитника получают консоляцию за недобор. Обязательства защиты на 6 / 7 / 8 / 9 / 10: 4 / 2 / 1 / 1 / 0. При двух вистах обязательства делятся поровну (на 8 и 9 возможна половина очка обязательства). Недобор пишется в гору.</p><p>Итог: разница пули и горы относительно среднего по столу × 10, плюс исходящие висты, минус входящие. Таблица показывает десятые доли виста; победитель определяется без округления. Играем без полвиста, виста всветлую, мизера без прикупа и премий за прикуп. Это домашние соглашения, а не полный турнирный кодекс.</p><p><a href="https://www.pocketpref.ru/pref/rules/rules.phtml" target="_blank" rel="noopener">Кодекс преферанса ↗</a></p>`);
render();if(fresh)newDialog(true);else if(migrated)toast('Сохранённая партия продолжена с пулей до 20 очков');
