(function(global){
'use strict';
const SUITS=['♠','♣','♦','♥'], RANKS=['7','8','9','10','В','Д','К','Т'];
const bids=[];for(let n=6;n<=10;n++){if(n===9)bids.push({id:bids.length,n:0,s:-1,label:'Мизер'});for(let s=0;s<5;s++)bids.push({id:bids.length,n,s:s===4?-1:s,label:n+' '+(s===4?'БК':SUITS[s])});}
function deck(){return SUITS.flatMap((_,s)=>RANKS.map((_,r)=>({id:s*8+r,s,r})));}
function shuffle(cards,rng=Math.random){for(let i=cards.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards;}
function sort(h){return h.sort((a,b)=>a.s-b.s||b.r-a.r)}
function legal(hand,trick,trump,forced=-1){const lead=trick.length?trick[0].card.s:forced;if(lead<0)return hand;const matching=hand.filter(c=>c.s===lead);if(matching.length)return matching;const ts=hand.filter(c=>c.s===trump);return ts.length?ts:hand;}
function winner(trick,trump,forced=-1){let lead=forced>=0?forced:trick[0].card.s;if(!trick.some(t=>t.card.s===lead))lead=trick[0].card.s;let best=null;for(const item of trick){const power=item.card.s===trump?100+item.card.r:item.card.s===lead?50+item.card.r:item.card.r;if(!best||power>best.power)best={...item,power}}return best.player;}
function estimate(hand,s){let value=0;for(let suit=0;suit<4;suit++){const h=hand.filter(c=>c.s===suit).sort((a,b)=>b.r-a.r);h.forEach((c,i)=>{value+=c.r===7?1:c.r===6?.65:c.r===5?.35:c.r===4?.15:0;if(suit===s&&i>=2)value+=.65});if(suit===s)value+=Math.max(0,h.length-3)*.3;}return value;}
function botBid(state,p){const h=state.hands[p];const options=available(state,p);if(options.some(b=>b.n===0)&&h.every(c=>c.r<6)&&h.filter(c=>c.r<=2).length>=6)return options.find(b=>b.n===0);return options.find(b=>b.n>0&&estimate(h,b.s)+.9>=b.n)||null;}
function available(state,p){if(state.passed[p])return [];return bids.filter(b=>b.id>state.high&&((b.n===0)?!state.spoken[p]:state.spoken[p]!=='misere'));}
function create(target=10){if(![10,15,20].includes(target))throw Error('Выберите пулю 10, 15 или 20');return {version:2,target,round:0,dealer:2,scores:Array.from({length:3},()=>({pool:0,hill:0,whists:[0,0,0]})),history:[],log:[],phase:'ready'};}
function poolClosed(st){return st.scores.every(s=>s.pool>=st.target);}
function creditPool(st,p,amount){const own=Math.min(amount,Math.max(0,st.target-st.scores[p].pool));st.scores[p].pool+=own;amount-=own;while(amount>0){const candidates=[(p+1)%3,(p+2)%3].filter(q=>st.scores[q].pool<st.target).sort((a,b)=>st.scores[b].pool-st.scores[a].pool);if(!candidates.length){st.scores[p].hill-=amount;log(st,'Излишек '+amount+' очк. списан с горы '+['вашей','Алексея','Марии'][p]);break}const q=candidates[0],help=Math.min(amount,st.target-st.scores[q].pool);st.scores[q].pool+=help;st.scores[p].whists[q]+=help*10;amount-=help;log(st,['Вы','Алексей','Мария'][p]+' → '+['вы','Алексей','Мария'][q]+': помощь '+help+' очк., '+help*10+' вистов');}}
function restore(saved){if(!saved||![1,2].includes(saved.version)||!Array.isArray(saved.hands)||saved.hands.length!==3||!Array.isArray(saved.scores)||saved.scores.length!==3||!saved.scores.every(s=>Number.isFinite(s.pool)&&Number.isFinite(s.hill)&&Array.isArray(s.whists)&&s.whists.length===3&&s.whists.every(Number.isFinite))||!Array.isArray(saved.history)||!Array.isArray(saved.log))return null;if(saved.version===2)return [10,15,20].includes(saved.target)?saved:null;saved.version=2;saved.target=20;delete saved.total;const excess=saved.scores.map(s=>{const n=Math.max(0,s.pool-saved.target);s.pool=Math.min(s.pool,saved.target);return n});excess.forEach((n,p)=>{if(n)creditPool(saved,p,n)});if(poolClosed(saved))saved.phase='finished';else if(saved.phase==='finished')saved.phase='result';return saved;}
function log(st,msg){st.log.push(msg);st.log=st.log.slice(-50);}
function deal(st){if(poolClosed(st)){st.phase='finished';return}st.round++;st.dealer=(st.dealer+1)%3;const d=shuffle(deck());st.hands=[sort(d.slice(0,10)),sort(d.slice(10,20)),sort(d.slice(20,30))];st.talon=d.slice(30);st.tricks=[0,0,0];st.trick=[];st.completed=[];st.passed=[false,false,false];st.spoken=[false,false,false];st.high=-1;st.declarer=-1;st.contract=null;st.whist=[null,null,null];st.turn=(st.dealer+1)%3;st.first=st.turn;st.phase='auction';st.log=[];log(st,'Раздача '+st.round+'. Первое слово: '+['вы','Алексей','Мария'][st.first]);}
function bid(st,p,id){if(st.phase!=='auction'||st.turn!==p)throw Error('Сейчас не ваша очередь');if(id===null){st.passed[p]=true;log(st,['Вы','Алексей','Мария'][p]+': пас')}else{const b=available(st,p).find(b=>b.id===id);if(!b)throw Error('Недопустимая заявка');st.high=id;st.declarer=p;st.spoken[p]=b.n===0?'misere':true;log(st,['Вы','Алексей','Мария'][p]+': '+b.label)}const active=st.passed.filter(x=>!x).length;if(active===0){st.contract={n:-1,s:-1,label:'Распасы'};startPlay(st);return}if(active===1&&st.high>=0){st.contract={...bids[st.high]};st.hands[st.declarer]=sort(st.hands[st.declarer].concat(st.talon));st.phase='discard';st.turn=st.declarer;return}do{st.turn=(st.turn+1)%3}while(st.passed[st.turn]);}
function discard(st,ids){if(st.phase!=='discard'||ids.length!==2||new Set(ids).size!==2||!ids.every(id=>st.hands[st.declarer].some(c=>c.id===id)))throw Error('Выберите две карты');st.discarded=st.hands[st.declarer].filter(c=>ids.includes(c.id));st.hands[st.declarer]=st.hands[st.declarer].filter(c=>!ids.includes(c.id));st.phase='contract';}
function declare(st,id){if(st.phase!=='contract')throw Error('Неверный этап');const b=bids[id];if(!b||b.id<st.high||(st.contract.n===0?b.n!==0:b.n===0))throw Error('Контракт нельзя понизить');st.contract={...b};log(st,'Заказано: '+b.label);if(b.n===0){startPlay(st);return}st.phase='whist';st.turn=(st.declarer+1)%3;}
function whist(st,p,yes){if(st.phase!=='whist'||st.turn!==p)throw Error('Неверная очередь виста');st.whist[p]=!!yes;log(st,['Вы','Алексей','Мария'][p]+': '+(yes?'вист':'пас'));const other=(p+1)%3;if(other===st.declarer){if(!st.whist.some(Boolean)){st.tricks[st.declarer]=st.contract.n;settle(st)}else startPlay(st)}else st.turn=other;}
function startPlay(st){st.phase='play';st.turn=st.first;st.trick=[];}
function forced(st){return st.contract.n===-1&&st.completed.length<2?st.talon[st.completed.length].s:-1;}
function play(st,p,id){if(st.phase!=='play'||st.turn!==p||st.trick.length===3)throw Error('Сейчас не ваша очередь');const cards=legal(st.hands[p],st.trick,st.contract.s,forced(st));const card=cards.find(c=>c.id===id);if(!card)throw Error('Нужно дать масть, а при её отсутствии — козыря');st.hands[p]=st.hands[p].filter(c=>c.id!==id);st.trick.push({player:p,card});if(st.trick.length===3){st.trickWinner=winner(st.trick,st.contract.s,forced(st));st.tricks[st.trickWinner]++;st.phase='trickEnd';}else st.turn=(p+1)%3;}
function collect(st){if(st.phase!=='trickEnd')throw Error('Взятка не завершена');st.completed.push(st.trick);st.turn=st.trickWinner;st.trick=[];if(st.completed.length===10)settle(st);else st.phase='play';}
function settle(st){const c=st.contract;let summary;if(c.n===-1){st.scores.forEach((x,p)=>x.hill+=st.tricks[p]);summary='Распасы: '+st.tricks.join(' / ')}else{const p=st.declarer,score=st.scores[p],cost=c.n===0?10:(c.n-5)*2,loss=c.n===0?st.tricks[p]:Math.max(0,c.n-st.tricks[p]);if(!loss)creditPool(st,p,cost);else score.hill+=loss*cost;if(c.n>0){const defenders=[0,1,2].filter(x=>x!==p),v=defenders.filter(x=>st.whist[x]);for(const q of defenders){if(st.whist[q])st.scores[q].whists[p]+=st.tricks[q]*cost;if(loss)st.scores[q].whists[p]+=loss*cost;}const need=c.n===6?4:c.n===7?2:c.n<=9?1:0;if(v.length===1){const q=v[0],missing=Math.max(0,need-defenders.reduce((a,x)=>a+st.tricks[x],0));st.scores[q].hill+=missing*cost;const pass=defenders.find(x=>x!==q);st.scores[q].whists[p]+=st.tricks[pass]*cost;}else if(v.length===2){for(const q of v)st.scores[q].hill+=Math.max(0,need/2-st.tricks[q])*cost;}}summary=['Вы','Алексей','Мария'][p]+' · '+c.label+' · '+(loss?'подсад '+loss:'сыграно');}st.result=summary;st.history.push({round:st.round,label:summary,tricks:[...st.tricks]});log(st,summary);st.phase=poolClosed(st)?'finished':'result';}
function totals(st){const sum=st.scores.reduce((a,x)=>a+x.hill-x.pool,0);return st.scores.map((x,p)=>((sum-3*(x.hill-x.pool))*10+3*(x.whists.reduce((a,n)=>a+n,0)-st.scores.reduce((a,y)=>a+y.whists[p],0)))/3);}
function standings(st){const values=totals(st),rows=st.scores.map((s,player)=>({player,pool:s.pool,hill:s.hill,whists:s.whists.reduce((a,n)=>a+n,0)-st.scores.reduce((a,y)=>a+y.whists[player],0),total:values[player]})).sort((a,b)=>b.total-a.total||a.player-b.player);rows.forEach((r,i)=>r.place=i&&r.total===rows[i-1].total?rows[i-1].place:i+1);return rows;}
function botDiscard(st){const h=st.hands[st.declarer];return [...h].sort((a,b)=>{if(st.contract.n===0)return b.r-a.r;const v=c=>c.r+(c.s===st.contract.s?10:0)+(h.filter(x=>x.s===c.s).length>2?2:0);return v(a)-v(b)}).slice(0,2).map(c=>c.id);}
function botCard(st,p){const cs=legal(st.hands[p],st.trick,st.contract.s,forced(st));const avoid=st.contract.n===-1||(st.contract.n===0&&p===st.declarer);const ascending=[...cs].sort((a,b)=>a.r-b.r);if(!st.trick.length){if(avoid)return ascending[0];if(st.contract.n===0)return ascending[0];return [...cs].sort((a,b)=>(b.r+(b.s===st.contract.s?3:0))-(a.r+(a.s===st.contract.s?3:0)))[0];}const winning=cs.filter(c=>winner([...st.trick,{player:p,card:c}],st.contract.s,forced(st))===p).sort((a,b)=>a.r-b.r);const losing=ascending.filter(c=>!winning.some(w=>w.id===c.id));if(avoid)return losing.at(-1)||ascending[0];const current=winner(st.trick,st.contract.s,forced(st));if(st.contract.n>0&&p!==st.declarer&&current!==st.declarer)return ascending[0];return winning[0]||ascending[0];}
const api={SUITS,RANKS,bids,deck,shuffle,sort,legal,winner,estimate,available,create,restore,poolClosed,creditPool,standings,deal,bid,discard,declare,whist,play,collect,forced,totals,botBid,botDiscard,botCard};if(typeof module!=='undefined')module.exports=api;global.Pref=api;
})(typeof window==='undefined'?globalThis:window);
